[package]
name = "rsi-ui-portable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rsi-meta = { path = "../../rsi-meta/core" }
rsi-ui = { path = "../ui" }
rsi-ui-protocol = { path = "../ui-protocol" }
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-api-portable = { path = "../../rsi-api/portable" }
rsi-host = { path = "../../rsi-host/core" }
rsi-application = { path = "../application" }
tokio-util.workspace = true
async-trait.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[lints]
workspace = true
