[package]
name = "rsi-session-files-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
rsi-meta = { path = "../../rsi-meta/core" }
rsi-ui = { path = "../ui" }
rsi-client = { path = "../client" }
rsi-session-protocol = { path = "../session-protocol" }
rsi-session-files = { path = "../session-files" }
rsi-files-protocol = { path = "../../rsi-files/protocol" }
rsi-tools-protocol = { path = "../../rsi-tools/protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
