[package]
name = "rsi-agent-store-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-execution-protocol = { path = "../../rsi-execution/protocol" }
async-trait.workspace = true
rsi-agent-session-protocol = { path = "../session-protocol" }
rsi-ai-protocol = { path = "../../rsi-ai/protocol" }
rsi-meta-contract = { path = "../../rsi-meta/contract" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
