[package]
name = "rsi-web-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-api-http = { path = "../../rsi-api/http" }
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-meta = { path = "../../rsi-meta/core" }
serde.workspace = true
serde_json.workspace = true
tokio-util.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
rsi-host = { path = "../../rsi-host/core" }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
