[package]
name = "rsi-process-output-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-meta = { path = "../../rsi-meta/core" }
rsi-process = { path = "../core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
rsi-api = { path = "../../rsi-api/core" }
rsi-process-local = { path = "../local" }
rsi-sandbox = { path = "../../rsi-sandbox/core" }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
