[package]
name = "rsi-credentials-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-credentials-protocol = { path = "../protocol" }
rsi-meta = { path = "../../rsi-meta/core" }
serde_json.workspace = true

[lints]
workspace = true
