[package]
name = "rsi-ssh-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rsi-ssh-protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
tokio-util.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["time", "test-util", "rt-multi-thread"] }

[lints]
workspace = true
