[package]
name = "rsi-ai-plugin-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rsi-ai.workspace = true
rsi-ai-meta.workspace = true
rsi-ai-openai.workspace = true
rsi-ai-provider.workspace = true
rsi-ai-transport.workspace = true
rsi-meta-plugin.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
