[package]
name = "rsi-api-uds-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[target.'cfg(unix)'.dependencies]
async-stream.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper = { workspace = true, features = ["client", "http1"] }
hyper-util.workspace = true
rsi-api-protocol = { path = "../protocol" }
rsi-api-client = { path = "../client" }
rsi-meta = { path = "../../rsi-meta/core" }
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["net", "rt"] }
tokio-util.workspace = true

[dev-dependencies]
rsi-api = { path = "../core" }
rsi-api-http = { path = "../http" }
tempfile.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "time"] }

[lints]
workspace = true
