[package]
name = "rsi-process-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rsi-sandbox = { path = "../../rsi-sandbox/core" }
async-trait.workspace = true
getrandom.workspace = true
hex.workspace = true
rsi-meta = { path = "../../rsi-meta/core" }
rsi-process = { path = "../core" }
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["process", "fs", "event"] }

[target.'cfg(target_os = "linux")'.dependencies]
portable-pty.workspace = true

[dev-dependencies]
rsi-sandbox-local = { path = "../../rsi-sandbox/local" }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time", "test-util"] }

[lints]
workspace = true
