[package]
name = "rsi-meta-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
hex.workspace = true
libloading.workspace = true
libc.workspace = true
rsi-meta = { path = "../core" }
rsi-meta-plugin = { path = "../plugin" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
tokio-util.workspace = true

[lints]
workspace = true
