[package]
name = "rsi-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
rsi-workbench-ui = { path = "../workbench-ui" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
rsi-web-assets-api = { path = "../web-assets-api" }
rsi-session-tree-ui = { path = "../session-tree-ui" }
rsi-session-files-ui = { path = "../session-files-ui" }
rsi-ui = { path = "../ui" }
rsi-session-ui = { path = "../session-ui" }
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-client-composition = { path = "../client-composition" }
rsi-host = { path = "../../rsi-host/core" }
rsi-meta = { path = "../../rsi-meta/core" }
rsi-meta-execution = { path = "../../rsi-meta/execution" }
tokio = { workspace = true, features = ["sync", "macros"] }
rsi-gui = { path = "../gui" }
web-sys = { workspace = true, features = ["Crypto", "WorkerGlobalScope"] }
js-sys.workspace = true
rsi-api-browser-client = { path = "../../rsi-api/browser-client" }
rsi-credentials-protocol = { path = "../../rsi-credentials/protocol" }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
zeroize.workspace = true

[lints]
workspace = true
