[package]
name = "rsi-build-info"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[build-dependencies]
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
