[package]
name = "rsi-meta-profile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
rhai.workspace = true
rsi-meta = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true

[target.'cfg(windows)'.dependencies]
same-file.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libc.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
rhai = { workspace = true, features = ["wasm-bindgen"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time", "test-util"] }

[lints]
workspace = true
