[package]
name = "rsi-storage-json"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
libc.workspace = true
rsi-meta = { path = "../../rsi-meta/core" }
rsi-storage = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
same-file.workspace = true
tokio.workspace = true

[dev-dependencies]
rsi-storage-domain = { path = "../domain" }
tempfile.workspace = true

[lints]
workspace = true
