[package]
name = "rsi-sandbox-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-meta = { path = "../../rsi-meta/core" }
rsi-sandbox = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
tempfile.workspace = true

[dev-dependencies]

[lints]
workspace = true
