[package]
name = "rsi-meta-native-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
async-trait.workspace = true
hex.workspace = true
libloading.workspace = true
libc.workspace = true
rsi-meta = { path = "../core" }
rsi-meta-native = { path = "../native" }
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "time", "test-util"] }
tokio-util.workspace = true

[lints]
workspace = true
