[package]
name = "rsi-web-assets-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rsi-api-protocol = { path = "../../rsi-api/protocol" }
rsi-ui-protocol = { path = "../ui-protocol" }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rsi-meta = { path = "../../rsi-meta/core" }
rsi-web-assets = { path = "../web-assets" }
async-trait.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
rsi-api = { path = "../../rsi-api/core" }
rsi-host = { path = "../../rsi-host/core" }
rsi-api-http = { path = "../../rsi-api/http" }
sha2.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
