[package]
name = "rsi-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-meta-contract = { path = "../../rsi-meta/contract" }
rsi-sandbox = { path = "../../rsi-sandbox/core" }
thiserror.workspace = true

[lints]
workspace = true
