[package]
name = "rsi-directory-picker-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
rsi-meta = { path = "../../rsi-meta/core" }
rsi-api-protocol = { path = "../../rsi-api/protocol" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
